name: Deploy to Puter

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy website
        uses: HeyPuter/puter-subdomain-deploy-action@v1.0.6
        with:
          subdomain: rey-hello-site2
          source_path: dist
          puter_path: ~/Sites/rey-hello-site/
          puter_token: ${{ secrets.PUTER_TOKEN }}
